### ISSUE TITLE
I can't complie it, and I don't konwn what had happend.

### ISSUE THREAD

**Issue by UPON-2021** [sfc9982/Simple-12306#1]
I have ues git clone, then I use cmake and make.

I don't understand the flie "编译注意事项.txt", because it is 2 difficult to understand and 2 short and sweet.

You didn't declear which system can run it, i thint it can't be run in anyway

here is the picture

![IMG_20220601_191712](https://user-images.githubusercontent.com/93699115/171392505-cb416efd-dfa0-436e-a62e-24e2bb24d7a5.jpg)

My conputers runs Windows 11 Dev and my c plus plus version is msvc

so can you repair it at once?

Plz hurry!!!!!!!!  :{

**Comment by sfc9982** [comment]
You didn't include some important C/C++ library such as `conio.h`.

**Comment by sfc9982** [comment]
@UPON-2021 **STFW** and **RTFM**!!!
